Update copy

diff --git a/S3automation/copy b/S3automation/copy
--- a/S3automation/copy
+++ b/S3automation/copy
@@ -1,26 +1,96 @@
-## execute shell process
-- hosts: sitserver
-  tasks:
-    - name: CHECK SPACE DETAILS
-      shell: df -kh
-      register: command_out
-    
-    - name: Format disk usage table
-      shell: df -kh | awk 'NR==1{print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6} NR>1{print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6}' | column -t
-      register: formatted_output
-    
-    - name: Send email
-      mail:
-        host: "mailrelay-prod.meta.spectrum.net"
-        from: "Mobile2.0-DevOps <Mobile2.0-DevOps@charter.com>"
-        to: "C-Venugopal.Velagani@charter.com,C-Sanket.Kurane@charter.com"
-        subject: "Weekly Metrics Reports for Mediation Server Health Checks"
-        body: |
+#!/bin/sh
+WORKSPACE=${CI_PROJECT_DIR}
+cd $WORKSPACE
 
-          Hi All,
-          Please find the Weekly Metrics Reports for Mediation Server Health Checks:
-          {{ formatted_output.stdout }}
-         
-          Thanks,
-          MDA-SRE Team.
-      delegate_to: localhost
+source $WORKSPACE/config/${env}-config.properties
+
+aws_profile=profile
+profile=${!aws_profile}
+
+aws_region=region
+region=${!aws_region}
+
+result_file=$1
+status_file=$2
+error_flag="false"
+
+if [[ -f "$result_file" ]]; then
+   rm -rf "$result_file"
+fi
+
+if [[ -f "$status_file" ]]; then
+   rm -rf "$status_file"
+fi
+
+if [[ $profile == "" ]]; then
+    echo "Add AWS profile details in awsprofiledetails for $env"
+    exit 1;
+else        
+    echo "AWS PROFILE: $profile"
+fi
+
+# switching AWS profile
+echo "AWS Region: $region"
+export AWS_PROFILE=$profile
+
+ReplicationTaskIdentifier=$(aws --region $region dms describe-replication-tasks --filters "Name=replication-task-arn,Values=$replication_task_arn" --query "ReplicationTasks[0].ReplicationTaskIdentifier")
+echo "DMS Task Name : $ReplicationTaskIdentifier"
+
+SourceEndpointArn=$(aws --region $region dms describe-replication-tasks --filters "Name=replication-task-arn,Values=$replication_task_arn" --query "ReplicationTasks[0].SourceEndpointArn")
+SourceEndpointURL=$(aws --region $region dms describe-endpoints --filters "Name=endpoint-arn,Values=$SourceEndpointArn" --query "Endpoints[0].ServerName")
+echo "Source DB Enpoint URL : $SourceEndpointURL"
+
+TargetEndpointArn=$(aws --region $region dms describe-replication-tasks --filters "Name=replication-task-arn,Values=$replication_task_arn" --query "ReplicationTasks[0].TargetEndpointArn")
+TargetEndpointURL=$(aws --region $region dms describe-endpoints --filters "Name=endpoint-arn,Values=$TargetEndpointArn" --query "Endpoints[0].ServerName")
+echo "Target DB Enpoint URL : $TargetEndpointURL"
+
+# start DMS task
+echo "Starting DMS task"
+check_task_status=$(aws --region $region dms describe-replication-tasks --filters "Name=replication-task-arn,Values=$replication_task_arn" --query "ReplicationTasks[0].Status")
+if [ "${check_task_status}" != '"running"' ]; then
+    aws dms start-replication-task --replication-task-arn $replication_task_arn --start-replication-task-type reload-target
+else
+    echo "Task is already running!!"
+    exit 1
+fi
+
+if [ $? -eq 0 ]; then
+
+    while [ "${task_status}" != '"running"' ] && [ "${task_status}" != '"failed"' ]
+    do
+        echo "Checking status of DMS task"
+        task_status=$(aws --region $region dms describe-replication-tasks --filters "Name=replication-task-arn,Values=$replication_task_arn" --query "ReplicationTasks[0].Status")
+        echo "task status: $task_status"
+		sleep 15
+    done
+    if [ "$task_status" = '"running"' ]; then
+	   echo "DMS Task started successfully."
+
+	   echo "Waiting for replication-task to get completed"
+	   while [ "${rep_task_status}" != '"stopped"' ]
+       do       
+          rep_task_status=$(aws --region $region dms describe-replication-tasks --filters "Name=replication-task-arn,Values=$replication_task_arn" --query "ReplicationTasks[0].Status")
+          echo "replication task status: $rep_task_status"
+		  sleep 15
+       done
+	   
+	   #aws dms wait replication-task-stopped --filters Name="replication-task-arn",Values="$replication_task_arn"
+	   echo "DMS Task completed successfully."
+	   echo "DMS Task completed successfully." > $result_file
+
+    elif [ "$task_status" = '"failed"' ]; then 
+       echo "Error: DMS Task failed to start."
+       echo "DMS Task failed." > $result_file
+       error_flag="true"	   
+    fi
+else
+    echo "Something went wrong in starting DMS Task."
+    echo "Something went wrong in starting DMS Task, DMS Task failed." > $result_file
+	error_flag="true"
+fi
+
+if [[ "$error_flag" == "true" ]]; then 
+   echo "FAILED" > $status_file
+else
+   echo "SUCCESS" > $status_file
+fi
